version: '3'

networks:
  backend:
    external: true

services:
  csctracker:
    container_name: frontend
    hostname: frontend
    image: krlsedu/csctracker-frontend
    restart: always
    networks:
      - backend
