version: '3'

volumes:
  portainer-data:

networks:
  backend:
    external: true

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: 'portainer/portainer-ce:latest'
    networks:
      - backend
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data