version: '3'

networks:
  backend:
    external: true

services:
  csctracker:
    container_name: csctracker
    hostname: csctracker
    image: krlsedu/timetracker
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    ports:
      - "8090:8080"
    networks:
      - backend
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar app.jar"
    volumes:
      - /root/.timeTracker:/etc/timeTracker/.timeTracker