version: '3'
services:
  netdata:
    image: netdata/netdata:edge
    container_name: netdata
    hostname: wsl # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=07uMU02YwlqhIJltVbwtzl8AnVM_mLIMuhO56-DRRYpar2j92MLmm8i-5-BwlBKrwYPOb873WhNY1x3FEjWrG7hradu-obv8RF-m9QrCB3kcz8zbeSOSM_yym6TbqL7Jjq8bMXI
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=

volumes:
  netdataconfig:
  netdatalib:
  netdatacache: