version: '3'

networks:
  backend:
    external: true

services:
  csctracker:
    container_name: datasource
    hostname: datasource
    image: krlsedu/csctracker-datasource
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    networks:
      - backend
