version: '3'

networks:
  debeziun:
    driver: bridge

services:
  postgres:
    container_name: postgres_debeziun
    hostname: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - debeziun
    ports:
      - "5433:5432"
    command:
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - D:\Fontes\boilerplates\docker-compose\debezium\postgresql.conf:/etc/postgresql/postgresql.conf

  debezium:
    hostname: debezium
    image: debezium/server
    ports:
      - "8765:8080"
    networks:
      - debeziun
    depends_on:
      - redis
    volumes:
      - D:\Fontes\boilerplates\docker-compose\debezium\conf:/debezium/conf
    deploy:
      resources:
        limits:
          memory: 1024M

  redis:
    image: redis/redis-stack:7.0.6-RC4
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - debeziun
    volumes:
      - cache:/data
    deploy:
      resources:
        limits:
          memory: 1024M
volumes:
  cache:
    driver: local
  postgres-db: