version: '3'

services:
  ibmmq:
    image: ibmcom/mq
    hostname: ibmmq
    container_name: ibmmq
    ports:
      - "1414:1414"
      - "9463:9443"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
